apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage-pvc
spec:
  # 要設成 ReadWriteMany 才能平行擴展
  # 但先決條件是 StorageClass 要支援
  accessModes:
    - ReadWriteMany
  # 不同平台或供應商可能會有所不同
  storageClassName: openebs-rwx
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-deploy
  template:
    metadata:
      labels:
        app: app-deploy
    spec:
      containers:
        - name: app
          image: demo
          resources:
            requests:
              cpu: 64m
              memory: 64M
            limits:
              cpu: 128m
              memory: 128M
          ports:
            - name: app-port
              containerPort: 80
          # 獨立 env 檔案，方便管理及部署
          envFrom:
            - configMapRef:
                name: app-env
          volumeMounts:
            - mountPath: /app/storage
              name: app-storage
          # 確定新的 pod 已經可以正常服務後才砍掉舊的 pod
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
          # 定時檢查 pod 是否健康
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app-deploy
